### ISSUE TITLE
消息转发功能无效

### ISSUE THREAD

**Issue by TilyTao** [XiaMoHuaHuo-CN/CatSero#13]
### 功能描述

开启转发功能，然而他并没有转发任何一端的消息
```yaml
# 转发MC-QQ聊天
forward-chat:
  # 启用此功能
  enabled: true
  # 格式
  format:
    to-mc: "[%time%][QQ][%groupname%(%groupcode%)]%sendername%(%sendercode%):\n%message%"
    to-qq: "[MC]%player%:\n%message%"
  prefix:
    # 启用此功能
    enabled: false
    # 格式(只支持单个，字符，请勿输入多个)
    format:
      to-mc: "#"
      to-qq: "#"
  # 发到QQ自动清理消息中的颜色代码
  clean-colorcode: true
  # 使用MiraiMC内置绑定
  use-bind: false
```

### 使用方法

1.
