### ISSUE TITLE
[不影响使用]Whitelist开关逻辑存在问题

### ISSUE THREAD

**Issue by wanyanjiabin** [XiaMoHuaHuo-CN/CatSero#81]
### 问题描述

2.3版本重启之后,每当用户登录就会报错一次.不确定是否是BUG,仅反馈

### 复现方法

1. 

### 服务端版本

Paper-1.19.2

### CatSero 版本

2.3

### 服务端日志

```text
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] 捕获到一个错误
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] 错误类型: org.sqlite.SQLiteException
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] 捕获消息: [SQLITE_ERROR] SQL error or missing database (no such table: RECORDS)
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] 详细信息: [org.sqlite.core.DB.newSQLException(DB.java:1030), org.sqlite.core.DB.newSQLException(DB.java:1042), org.sqlite.core.DB.throwex(DB.java:1007), org.sqlite.core.NativeDB.prepare_utf8(Native Method), org.sqlite.core.NativeDB.prepare(NativeDB.java:137), org.sqlite.core.DB.prepare(DB.java:257), org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66), [QQ机器人]CatSero-2.3.jar//com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110), [QQ机器人]CatSero-2.3.jar//com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java), [QQ机器人]CatSero-2.3.jar//moe.xmcn.catsero.utils.WhiteListDatabase.getCode(WhiteListDatabase.java:266), [QQ机器人]CatSero-2.3.jar//moe.xmcn.catsero.listeners.qwhitelist.RefuseNoWhiteList.onPlayerPreLogin(RefuseNoWhiteList.kt:33), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor229.execute(Unknown Source), org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670), net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:431), net.minecraft.server.network.LoginListener$1.run(LoginListener.java:310), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base/java.lang.Thread.run(Thread.java:833)]
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] 如您认为这不是配置错误、网络原因导致的问题，请前往此处报告：
[13:19:34] [User Authenticator #0/WARN]: [CatSero] [Catch] https://github.com/XiaMoHuaHuo-CN/CatSero/issues
```

**Comment by wanyanjiabin** [comment]
虽然报错但是各项功能运行正常

**Comment by XiaMoHuaHuo-CN** [comment]
您备份数据库后删除原来的sqlite文件呢?

**Comment by wanyanjiabin** [comment]
不好意思,最近有点忙,耽误了
是这样,我**禁用了**白名单功能,因为使用了一个单独的web白名单插件.
在程序启动之后,目录下新建了一个名为 whitelist.db 的文件,但是大小是0KB,因该是空文件.
不知道是不是这个原因.

**Comment by wanyanjiabin** [comment]
**刚才我把配置文件改为了msyql 重启服务器之后,指定的数据库内没有新建表,依然是这个报错,只是改为了mysql报错.**

[21:35:43] [User Authenticator #0/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Starting...
[21:35:43] [User Authenticator #0/WARN]: [com.zaxxer.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[21:35:43] [User Authenticator #0/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Start completed.
[21:35:43 WARN]: [CatSero] [Catch] 捕获到一个错误
[21:35:43 WARN]: [CatSero] [Catch] 错误类型: java.sql.SQLSyntaxErrorException
[21:35:43 WARN]: [CatSero] [Catch] 捕获消息: Table 'catsero.RECORDS' doesn't exist
[21:35:43 WARN]: [CatSero] [Catch] 详细信息: [com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120), com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122), com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201), [QQ机器人]CatSero-2.3.jar//com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110), [QQ机器人]CatSero-2.3.jar//com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java), [QQ机器人]CatSero-2.3.jar//moe.xmcn.catsero.utils.WhiteListDatabase.getCode(WhiteListDatabase.java:266), [QQ机器人]CatSero-2.3.jar//moe.xmcn.catsero.listeners.qwhitelist.RefuseNoWhiteList.onPlayerPreLogin(RefuseNoWhiteList.kt:33), com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor229.execute(Unknown Source), org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77), co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76), org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70), org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670), net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:431), net.minecraft.server.network.LoginListener$1.run(LoginListener.java:310), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base/java.lang.Thread.run(Thread.java:833)]
[21:35:43 WARN]: [CatSero] [Catch] 如您认为这不是配置错误、网络原因导致的问题，请前往此处报告：
[21:35:43 WARN]: [CatSero] [Catch] https://github.com/XiaMoHuaHuo-CN/CatSero/issues

**手动新建一个RECORDS表,然后只有id 和 name 字段.之后报错就变了,没有捕获那一段了**

[21:40:58 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-3 - Starting...
[21:40:58 WARN]: [com.zaxxer.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[21:40:58 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-3 - Start completed.


**然后把目录下的 whitelist.db 文件删除.修改config配置文件为sqlite 然后重启服务器**
**重启之后,自动新建了 whitelist.db 文件,但是还是0KB,还是之前反馈的报错**
**一个不成熟的推测,是否是没有进行建表操作**

**Comment by wanyanjiabin** [comment]
提供一下我的配置文件,便于排查
config.yml
```
# CatSero Plugin Config
# Generate by CatSero v2.2

# 语言文件
locale: zh_CN

# bStats
bstats: true

# 检查更新
check-update:
  # 功能开关
  # true | false
  enable: false
  # 检查更新间隔
  # 单位: 秒
  interval: 3600
  # 版本模式
  mode: latest
  # 检查更新服务器API地址，一般情况请勿修改
  api-url: https://mcp.huahuo-cn.tk/api/CatSero/version

# JDBC
jdbc:
  # SQLite JDBC class名称
  sqlite-class-name: "org.sqlite.JDBC"
  # MySQL JDBC class名称
  mysql-class-name: "com.mysql.jdbc.Driver"
  # 数据储存方法
  # sqlite | mysql
  type: sqlite
  # MySQL设置
  mysql-config:
    # 地址
    host: localhost
    # 端口
    port: 3306
    # 用户名
    username: root
    # 密码
    password: 123456
    # 数据库名
    database: catsero
    # 时区
    timezone: "Asia/Shanghai"
    # 使用Unicode
    unicode: true
    # 数据库编码格式
    encoding: "UTF-8"
    # 使用SSL连接
    ssl: false

# 自定义QQ命令头
command-prefix:
  # 功能开关
  # true | false
  enable: false
  # 命令头
  prefix: ""

```

uses-config.yml
```
# CatSero UsesConfig
# Generate by CatSero v2.3

# 所有的发送至QQ群的消息都支持mirai码
# 参见：
# https://docs.mirai.mamoe.net/Messages.html#mirai-%E7%A0%81
# https://docs.mirai.mamoe.net/Messages.html#%E6%B6%88%E6%81%AF%E5%85%83%E7%B4%A0
# https://docs.mirai.mamoe.net/Messages.html#%E6%B6%88%E6%81%AF%E9%93%BE%E7%9A%84-mirai-%E7%A0%81

# 聊天转发
chat-forward:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 自动清理样式代码
  clean-stylecode:
    to-mc: false
    to-qq: true
  # 消息头检测
  # 只有消息以这个字符串开头才会被转发
  header:
    # 功能开关
    # true | false
    enable: false
    # 消息头设置
    prefix:
      to-mc: "#"
      to-qq: "#"
  # 允许游戏内玩家使用mirai码
  allow-miraicode: false
  # 过滤器
  # 检测到消息内含有列表中的文本
  filter:
    # 功能开关
    # true | false
    enable: false
    # 列表
    list:
      # 原生的列表
      via:
        to-mc: [ ]
        to-qq: [ ]
      # 从外部导入
      import:
        # 本地
        local: [ ]
        # 远程
        # 此处使用的是TrChat的默认远程源
        # 感谢南城提供的词库
        # CDN JsDelivr
        remote:
          - "https://cdn.jsdelivr.net/gh/Yurinann/Filter-Thesaurus-Cloud@main/database.json"
    # 替换成的字符
    replace: "**"
  # 使用MiraiMC内置绑定数据库查询QQ发言者名称
  use-bind: false
  # 格式
  format:
    # 内置占位符:
    # - %sender_permission%  发言者群权限(member，admin，owner)
    # - %name%  发言者名称
    # - %message%  消息
    to-mc: "&e[&a群消息&e] &b<%name%> &r%message%"
    # 内置占位符:
    # - %sender_permission%  发言者权限(player，admin)
    # - %name%  发言者名称
    # - %display_name%  发言者游戏中显示名称
    # - %message%  消息
    to-qq: "%name% : %message%"

# 发送玩家加入/退出消息
send-player-join-quit:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  # 内置占位符:
  # - %player% 加入玩家名称
  format:
    # 加入
    join: "%player% 加入了游戏"
    # 退出
    quit: "%player% 退出了游戏"
  # 需要拥有权限才会发送
  need-permission: false

# 发送玩家死亡消息
send-player-death:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  # 内置占位符:
  # - %player%  玩家名
  # - %message%  死亡消息
  format: "%player%死了,因为\n%message%"
  # 需要拥有权限才会发送
  need-permission: false

# 新人加入群欢迎
new-group-member:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  # 内置占位符:
  # - %at%  @新成员
  # - %code%  新成员QQ号
  format: "欢迎%at%（%code%）加入本群!\n1.请修改昵称为游戏ID \n2.群内发ID找管理加白名单 \n3.服务器IP请查看公告"

# 玩家解锁进度转发
send-advancement:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  # 内置占位符:
  # = %player%  玩家名
  # - %name%  进度名
  # - %description%  进度描述
  format: "%player% 达成了成就: %name%\n描述: %description%"
  # 需要拥有权限才会发送
  need-permission: false

# TPS获取
get-tps:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup

# 在线玩家获取
get-online-list:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  format:
    # 无论是否有玩家在线都会发送
    # 内置占位符:
    # - %count%  当前在线玩家数
    # - %max%  最大在线玩家数
    0: |-
      当前在线: %count%
      最大在线: %max%
    # 当有玩家在线才发送
    # 内置占位符:
    # - %count%  当前在线玩家数
    # - %max%  最大在线玩家数
    # - %list%  当前在线玩家列表
    1: |-
      玩家列表: %list%

# QQ白名单
qwhitelist:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 检查是否在群内
  # 若存在白名单但不在群内则视为无
  check-if-on-group: true
  # 自助申请白名单
  self-application:
    # 功能开关
    # true | false
    enable: false
    # 申请格式
    # 内置占位符:
    # - %name%  玩家名（只能设置一个）
    format: "!申请白名单 %name%"
    # 限制每个QQ只能拥有一个白名单
    a-qq-only-an-account: true

# 离群提示
group-member-leave:
  # 功能开关
  # true | false
  enable: true
  # Bot & Group设置
  var:
    # BotID
    bot: lxbot
    # GroupID
    group: lxgroup
  # 格式
  # 内置占位符:
  # - %name%  名称
  # - %code%  QQ号
  format: "%name%（%code%）永远的离开我们,T^T"


```
